apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: three-tier
data:
  default.conf: |
    server {
      listen 80;

      location / {
        root /usr/share/nginx/html;
        index index.html;
      }

      location /api {
        proxy_pass http://backend/index.php;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
      }
    }